### ISSUE TITLE
Update Elements

### ISSUE THREAD

**Issue by sudis** [aloshai/mongosha#3]
# Update Elements

A function that can make our work easier should come to the module. (`await db.update`) It will be able to change the content in any "set" data or "push" data. For example, let's register our data as follows.

```js
await db.set(`hollowking.${message.guild.id}`, {
    Name: "Sude Magda",
    Surname: "ALACATI",
    Points: 15
})
```

**>**

```js
hollowking: {
    "795019981493895168": {
        Name: "Sude Magda",
        Surname: "ALACATI",
        Points: 15
    }
}
```

But our grumpy daughter Magda doesn't seem to like her point. As her caregiver, we have to fix this problem. For this, we need to change the record in a data. 

```js
await db.update(`hollowking.${message.guild.id}`, {
    change: {
        Surname: "Wiśniewski"
    },
    add: {
        Points: +5
    },
    remove: {
        Name: "Sude"
    },
    create: {
        Voivodeship: "Warsaw"
    }
})
```

**>**

```js
hollowking: {
    "795019981493895168": {
        Name: "Magda",
        Surname: "Wiśniewski",
        Points: 20,
        Voivodeship: "Warsaw"
    }
}
```

Our grumpy daughter now has 20 points. We have to make a little more change before seeing the very rich father. A list of must-come is listed below. 

`Change:` It changes a data. If used in terms of number, it directly changes the place of the newly entered number without adding or subtracting.

`Add:` It is used on all types of data. If used on a number, it adds to the number's value. (Of course at the beginning of the number - if any, this is different.) If used on a string value, it performs direct concatenation. (Before: Date, After: Datesing. Adding Date String value to + "sing") 

`Decrease:` It does the subtraction in the same way

`Create:` It creates a separate data. Although unnecessary for "set" type data, it is very useful for "push" data.

`Remove:` It deletes a seperate data. Although unnecessary for "set" type data, it is very useful for "push" data.

## How will it work for push data?
There will be a value for each push. That is, first data, second data and third data under "push". These data will of course start from 0. The numbers of these data will be processed. For example, there are 15 pushed data under a database. We will have 15 numbers with a starting record from 0. 

```js
await db.update(`melcorn.${message.guild.name}[0]`, {
    change: (...)
})
```

Everything can be very complicated, but I am sure she will bring many changes behind her. "Plus why don't we create a separate record for each data and add or subtract from it more easily?" The best answer to the question may be speed and convenience. At the same time, keeping less data and gathering all data under one roof is an adequate answer.

With love!

**Comment by aloshai** [comment]
I wanted to add this feature for a long time. But my goal in Mongosha was to add easy-to-use features, such as `set` and `get` methods. This kind of feature seems to be quite detailed for Mongosha, but it is also useful.

In Mongosha, my priority is always to make something is easy-to-use.

**Comment by sudis** [comment]
Whether or not to use a function is up to one's own will. This is not an addition or adjustment to Mongosha's normal functions. Adding something that doesn't exist. The above mentioned data cannot be edited in any way. Even if you do not see it as a competitor, other easy-to-use MongoDB modules that are your competitors have such functions. The main reason Update, a function that does not exist and needs to be added, is that we cannot do this in any way. To summarize, let's assume that we don't have the "get" function. You say it can get complicated instead of adding something that isn't there. 

Sincerely.

**Comment by aloshai** [comment]
Before I add a feature to Mongosha, I need to make sure it meets my requirements.

These are respectively;
- Easy-to-use
- Functionality
- The interest and need for this

For this reason, it is not possible to say anything at the moment. However, your idea is pretty good, and it recently made it into the list of features I wanted to add.

Thank you!
